{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:19:40.706Z"}
{"__augmented":true,"code":"SQLITE_ERROR","errno":1,"level":"error","message":"Ошибка при получении настроек подключения: SQLITE_ERROR: no such table: connection_settings","stack":"Error: SQLITE_ERROR: no such table: connection_settings\n--> in Database#get('SELECT * FROM connection_settings WHERE id = ?', [ 1 ], [Function (anonymous)])\n    at C:\\Progs\\KVT\\src\\database.js:247:15\n    at new Promise (<anonymous>)\n    at Database.getConnectionSettings (C:\\Progs\\KVT\\src\\database.js:246:12)\n    at initializeTelegramBot (C:\\Progs\\KVT\\src\\server.js:16:39)\n    at Object.<anonymous> (C:\\Progs\\KVT\\src\\server.js:252:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)\n    at node:internal/main/run_main_module:36:49","timestamp":"2025-04-15T11:19:40.709Z"}
{"__augmented":true,"code":"SQLITE_ERROR","errno":1,"level":"error","message":"Ошибка при получении настроек подключения: SQLITE_ERROR: no such table: connection_settings","stack":"Error: SQLITE_ERROR: no such table: connection_settings\n--> in Database#get('SELECT * FROM connection_settings WHERE id = ?', [ 1 ], [Function (anonymous)])\n    at C:\\Progs\\KVT\\src\\database.js:247:15\n    at new Promise (<anonymous>)\n    at Database.getConnectionSettings (C:\\Progs\\KVT\\src\\database.js:246:12)\n    at startReading (C:\\Progs\\KVT\\src\\server.js:102:41)\n    at C:\\Progs\\KVT\\src\\server.js:260:5\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-04-15T11:19:40.713Z"}
{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:19:46.656Z"}
{"code":"SQLITE_ERROR","errno":1,"level":"error","message":"Ошибка сохранения новых настроек подключения: SQLITE_ERROR: 8 values for 9 columns","stack":"Error: SQLITE_ERROR: 8 values for 9 columns","timestamp":"2025-04-15T11:19:59.756Z"}
{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:20:47.772Z"}
{"__augmented":true,"code":"SQLITE_ERROR","errno":1,"level":"error","message":"Ошибка при получении настроек подключения: SQLITE_ERROR: no such table: connection_settings","stack":"Error: SQLITE_ERROR: no such table: connection_settings\n--> in Database#get('SELECT * FROM connection_settings WHERE id = ?', [ 1 ], [Function (anonymous)])\n    at C:\\Progs\\KVT\\src\\database.js:247:15\n    at new Promise (<anonymous>)\n    at Database.getConnectionSettings (C:\\Progs\\KVT\\src\\database.js:246:12)\n    at initializeTelegramBot (C:\\Progs\\KVT\\src\\server.js:16:39)\n    at Object.<anonymous> (C:\\Progs\\KVT\\src\\server.js:252:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)\n    at node:internal/main/run_main_module:36:49","timestamp":"2025-04-15T11:20:47.775Z"}
{"__augmented":true,"code":"SQLITE_ERROR","errno":1,"level":"error","message":"Ошибка при получении настроек подключения: SQLITE_ERROR: no such table: connection_settings","stack":"Error: SQLITE_ERROR: no such table: connection_settings\n--> in Database#get('SELECT * FROM connection_settings WHERE id = ?', [ 1 ], [Function (anonymous)])\n    at C:\\Progs\\KVT\\src\\database.js:247:15\n    at new Promise (<anonymous>)\n    at Database.getConnectionSettings (C:\\Progs\\KVT\\src\\database.js:246:12)\n    at startReading (C:\\Progs\\KVT\\src\\server.js:102:41)\n    at C:\\Progs\\KVT\\src\\server.js:260:5\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-04-15T11:20:47.779Z"}
{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:20:49.301Z"}
{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:21:01.679Z"}
{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:22:39.678Z"}
{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:22:47.839Z"}
{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:23:26.018Z"}
{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:23:34.384Z"}
{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:24:50.000Z"}
{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:26:16.486Z"}
{"level":"info","message":"Подключение к базе данных успешно","timestamp":"2025-04-15T11:27:41.786Z"}
